### ISSUE TITLE
Pipe Command Line Interface (opk-pipe-cli)

### ISSUE THREAD

**Issue by rjcorwin** [open-eio/Open-Pipe-Kit-Project#3]
A command line way to create and configure a pipe to pull data from a sensor and push that data to any database.  At the moment I'm conceptualizing the command line workflow as you'll see in the comments below. I post every time I come up with a new idea. Your feedback is greatly appreciated!
- [Current command line software repo here](https://github.com/open-eio/Pipe-Engine)
- [Early draft here](https://github.com/open-eio/Pipe-Engine/blob/master/README.md)

Current working example (requires node v0.10.26 due to a dependency in `opk-temper1-cli` and a temper1 temperature sensor to pull data from):

```
#
# Step 0: Install the pipe command
#
npm install -g opk-pipe-cli

#
# Step 1: Create a new pipe
#
mkdir pipe1
cd pipe1
pipe init

#
# Step 2: Pull data from a sensor driver
#
# Add the temper1 temperature sensor driver and install it
git clone https://github.com/open-eio/opk-temper1-cli.git
./opk-temper1-cli/install
# Configure the driver. The configure command will give options you'll need
# and possible values for those options.
./opk-temper1-cli/configure
pipe config opk-temper1-cli.path USB_0c45_7401_14100000
# Configure the pipe to pull from this sensor and then test it
pipe config pipe.pull opk-temper1-cli
pipe pull

#
# Step 3: Push data to a database driver
#
# Add the phant database driver and configure it
git clone https://github.com/open-eio/opk-phant-cli.git
./opk-phant-cli/install
# Configure the driver. The configure command will give options you'll need
# and possible values for those options.
./opk-phant-cli/configure
pipe config opk-phant-cli.url http://data.sparkfun.com
pipe config opk-phant-cli.public_key RM1nQNbVRGtaMMgvVz8Y
pipe config opk-phant-cli.private_key lz6d0j7KxPH1VVryqMw5
pipe config opk-phant-cli.field_name temp
# Configure the pipe to push to this database and then test it
pipe config pipe.push opk-phant-cli
pipe push 42
# Check for your new data at https://data.sparkfun.com/streams/RM1nQNbVRGtaMMgvVz8Y

#
# Step 4: Configure the pump to run every five seconds and start it
#
pipe config pump.interval 5000
pipe pump
```

**Comment by rjcorwin** [comment]
Here's an idea on the [command line usage](https://gist.github.com/rjsteinert/ff96e7a01438f6e5991b) of this.  A command called `thing`.

**Comment by rjcorwin** [comment]
Alrighty. We have ourselves a start with tag release `0.0.5`. The following will log a random number to your screen every 5 seconds. `npm` command is a dependency (install nodejs).

```
$ npm install -g pipething
$ mkdir MyPipe
$ cd MyPipe
$ pipe init
$ npm install pipething_random
$ pipe thing pipething_random
$ npm install pipething_logger
$ pipe reservoir pipething_logger
$ pipe interval 5000
$ pipe watch
```

Next step is to write a Thing driver that's cooler than a random number generator and a Reservoir driver cooler than something that just logs to the screen. That exercise will give me an idea of how things need to shape up.

**Comment by rjcorwin** [comment]
Idea on making it more git-like...

```
$ npm install -g pipething
$ pipe
Hello. I am PipeThing. I will pull data from things and send that data to reservoirs.
$ mkdir MyPipe
$ cd MyPipe
$ pipe init
$ pipe thing add random_number_generator http://github.com/rjsteinert/thingpipe-thing-random_number_generator.git
$ pipe reservoir add logger http://github.com/rjsteinert/thingpipe-reservoir-logger.git
$ pipe pull random_number_generator
45
$ pipe push logger "42"
42
$ pipe interval 5000
$ pipe watch
24
47
98
12
...
```

**Comment by rjcorwin** [comment]
Better name, `thingpipe` as opposed to `pipething`. Also, more comments and also install commands for things and reservoirs.

```
$ npm install -g thingpipe
$ pipe
Hello. I am ThingPipe. I will pull data from things and send that data to reservoirs.
$ mkdir MyPipe
$ cd MyPipe
$ # Similar to `git init`
$ pipe init
$ # Similar to `git remote add`
$ pipe thing add random_number_generator http://github.com/rjsteinert/thingpipe-thing-random_number_generator.git
$ # Similar to `git fetch`
$ pipe install random_number_generator 
$ pipe reservoir add logger http://github.com/rjsteinert/thingpipe-reservoir-logger.git
$ pipe install logger
$ # Similar to git pull... kinda
$ pipe pull random_number_generator
45
$ # Similar to git push... kinda
$ pipe push logger "42"
42
$ pipe interval 5000
$ pipe watch
24
47
98
12
...
```

**Comment by rjcorwin** [comment]
Before I forget.... Mike McNeil's talk on Node Machines could provide some inspiration on drivers/plugins/functions/commands whatever we call them. Their goal is making functions easily reusable in other programs, I think our goal is making commands for things and reservoirs reusable outside of the context of Open Pipe Kit.

http://node-machine.org/

**Comment by rjcorwin** [comment]
Inspired by last week's OPK Hangout, I came up with an example that is more focused on multiple pipes and also a pump concept. This direction is more like docker and I'm thinking probably makes more sense than the `mkdir myPipe; cd myPipe; pipe init;` direction even though I like how hands on that is. In this example I also start thinking about real sensors drivers (grovepi_temp_pro) and real databases (phant). I shy away from the "thing" and "reservoir" terms and stick with the general "driver" term that could have many different types. 

```
$ npm install -g thingpipe
$ pipe
Hello. I am ThingPipe. I create pipes that direct the flow of data from sensors to databases. I can also create pumps to control the flow.
$ # Let's get started with adding sensor and database drivers.
$ pipe driver clone grovepi_temp_pro http://github.com/rjsteinert/thingpipe-sensor-grovepi_temp_pro.git
grovepi_temp_pro (sensor) now available
$ pipe driver clone phant http://github.com/rjsteinert/thingpipe-database-phant.git
phant (database) now available
$ pipe driver
name                         type           status          version    origin
grovepi_temp_pro             sensor         not installed   0.2.1      http://github.com/rjsteinert/thingpipe-thing-grovepi_temp_pro.git
phant                        database       not installed   0.1.0      http://github.com/rjsteinert/thingpipe-reservoir-phant.git
$ # Install the drivers now.
$ pipe install dht11_temperature
Successfully installed grovepi_temp_pro
$ pipe install phant
Successfully installed phant
$ # Configure the drivers. These will be global settings for a kind of "global" pipe on the device.
$ pipe config global driver.phant.url "https://data.sparkfun.com"
$ pipe config global driver.phant.stream_id "g6DJEnagnohd3pVnY1j5"
$ # Now let's try out these drivers.
$ pipe pull grovepi_temp_pro
23
$ pipe push phant "42"
Pushed 42 to phant at https://data.sparkfun.com/streams/g6DJEnagnohd3pVnY1j5
$ # With a command line trick, we combine the two.
$ pipe push phant `pipe pull grovepi_temp_pro`
Pushed 23 to phant at https://data.sparkfun.com/streams/g6DJEnagnohd3pVnY1j5
$
$
$
$ # Now lets create a pipe that connects the two so we can then manage the flow of data with a pump.
$ pipe create pipe pipe1
$ # Connect to pipe1 the grovepi_temp_pro as the source and the phant as the destination.
$ pipe connect pipe1 grovepi_temp_pro phant
$ # Now lets override the global values on these drivers.
$ pipe config pipe1 driver.phant.url "https://data.sparkfun.com"
$ pipe config pipe1 driver.phant.stream_id "wpKwzOZaVotqOz0XJq6p"
$ # Now we can use the pump command to do a pull and then push given the pipe's settins.
$ pipe pump pipe1
Pushed 23 to phant at https://data.sparkfun.com/streams/wpKwzOZaVotqOz0XJq6p
$ # Review the status of the pipe(s).
$ pipe -ls
... @todo
$
$
$
$ # Let's create a pump now that will manage the flow of data in pipe1.
$ pipe create pump pump1
$ pipe config pump1 interval 5000
$ pipe config pump1 capacity 4
$ pipe connect pipe1 pump1
$ pipe start pump1
$ # Now every 5 seconds the pump will pull and that data will stay in the pipe until a capacity of 4 is reached, at which point the pump will flush the pipe with pipe push.
Pushed 23,23,24,23 to phant at https://data.sparkfun.com/streams/wpKwzOZaVotqOz0XJq6p
$
$
```

**Comment by rjcorwin** [comment]
Now tracking the evolution of this example exercise at https://github.com/open-eio/Open-Pipe-Kit/blob/gh_pages/pipe-cli.md

**Comment by chrowe** [comment]
I like this because it is more focused on the fact that you are running a service (pump) and that pipe knows about all the installed drivers.

One downside of this approach is that it is less clear to me where all this stuff is stored. Before it seemed that everything I needed to connect a sensor to a data store was all in one directory which was nice.

Question:  When you install a driver, does that make it available or is it actually connecting to a specific sensor? What is "dht11_temperature"? It seems like once you clone a driver you have it to use with as many sensors as you want and that installing it would connect it to a specific sensor. I am not seeing how you choose which sensor you connect to though.

**Comment by rjcorwin** [comment]
@chrowe Good points, good questions. I've been thinking about them, don't have answers to all of them yet. I'm taking a step back from multi-pipe management for a bit. Still not sure it makes sense to tackle that right away. In particular I want the command to be easy to get started with. Multi-pipe management could be there when you're ready for the next level. For some folks that will happen pretty quickly but I do personally feel a need for something like the following. It's an example of something I'm currently working on with real drivers. Still not able to do it quite this way but this is the current best idea.

```
$ npm install -g thingpipe
$ # Create a pipe
$ mkdir pipe1
$ cd pipe1
$ pipe init
$ # Clone, install, and configure the simpleserial sensor driver
$ pipe driver clone grovepi_temp_pro http://github.com/open-eio/thingpipe-simpleserial.git
$ pipe install simpleserial
$ pipe config driver.simpleserial.serial_port "/dev/ttyACM0"
$ # Clone, install, and configure the phant database driver
$ pipe driver clone phant http://github.com/rjsteinert/thingpipe-database-phant.git
$ pipe install phant
$ pipe config driver.phant.url "https://data.sparkfun.com"
$ pipe config driver.phant.stream_id "g6DJEnagnohd3pVnY1j5"
$ pipe config driver.phant.private_key "nagnsds0johdwee9dh"
$ # Configure the pipe to pull every 1 second and then push when a capacity of 5 is reached
$ pipe config pipe.sensor simpleserial
$ pipe config pipe.database phant
$ pipe config pipe.capacity 5
$ pipe config pump.interval 1000
$ pipe watch 
```

**Comment by rjcorwin** [comment]
And here's another version. More focused, has `init`, `clone`, `driver`, `config`, and `pump` commands.

```
pipe <command>
  init : Creates a `config.json` file and a `drivers` folder in the directory you are in 
  clone <gitRepositoryLocation> : Clones a git repository into the drivers folder
  driver <driverName> <command> [<option> <option> ...] : A shortcut command that translate to `./divers/thingpipe-<driverName>/<command> [<option> <option> ...]
  config <key> <value> : A command that adds or changes an entry in the `config.json` file
  pump <operation> : A simple pump that you can configure to run at an interval and then start
```

```
$ # Install the pipe command
$ npm install -g thingpipe
$
$ # Create a pipe
$ mkdir pipe1
$ cd pipe1
$ pipe init
$
$ # Clone, install, and configure the simpleserial driver
$ pipe clone http://github.com/open-eio/thingpipe-simpleserial.git
$ pipe driver simpleserial install
$ pipe config driver.simpleserial.port "/dev/ttyACM0"
$
$ # Clone, install, and configure the phant driver
$ pipe clone http://github.com/rjsteinert/thingpipe-phant.git
$ pipe driver phant install
$ pipe config driver.phant.url "https://data.sparkfun.com"
$ pipe config driver.phant.stream_id "g6DJEnagnohd3pVnY1j5"
$ pipe config driver.phant.private_key "nagnsds0johdwee9dh"
$
$ # Configure the pipe's behaviors
$ pipe config pipe.pull simpleserial
$ pipe config pipe.push phant
$ pipe config pipe.capacity 5
$ 
$ # Configure a pump and start it
$ pipe config pump.interval 1000
$ pipe pump start 
```

**Comment by rjcorwin** [comment]
The most important part about this work is not pipe-cli code but the standard for the Pipe Drivers (pd). The goal of pipe-cli could be to become a thin wrapper around Pipe Drivers.

A Pipe Driver is a folder of files that are commands. Possible standard commands in a Pipe Driver (pd) folder are as follows.

```
help: describes the other commands and the corresponding parameters
push: A command for pushing data or a command to some thing
pull: A command for pulling data from some thing 
listen: A command for listening for data or a command from some thing 
install: A command for installing necessary pieces required for other commands to work.
```

The pipe-cli would then be a wrapper around the Pipe drivers by maintaining a config.json file that fills out what parameters to use on pd commands like `push` and `pull`. Here's the potential docs on the pipe-cli and then an example usage that actually tells the user how their pipe commands are being transformed to utilize the pd commands.

```
pipe <command>
  init : Creates a `config.json` file and a `drivers` folder in the directory you are in 
  clone <gitRepositoryLocation> : Clones a git repository into the drivers folder
  driver <driverName> <command> [<option> <option> ...] : A shortcut command that translate to `./divers/thingpipe-<driverName>/<command> [<option> <option> ...]
  config <key> <value> : A command that adds or changes an entry in the `config.json` file
  pump <operation> : A simple pump that you can configure to run at an interval and then start
```

```
$ # Install the pipe command
$ npm install -g pipe-cli
$
$ # Create a pipe
$ mkdir pipe1
$ cd pipe1
$ pipe init
$
$ # Clone, install, and configure the simpleserial driver
$ pipe clone http://github.com/open-eio/pd_grove_temperature.git
$ pipe driver pd_grove_temperature install
$ pipe config driver.pd_grove_temperature.pull.port "/dev/ttyACM0"
$
$ # Clone, install, and configure the phant driver
$ pipe clone http://github.com/rjsteinert/pd_phant.git
$ pipe driver pd_phant install
$ pipe config driver.pd_phant.push.url "https://data.sparkfun.com"
$ pipe config driver.pd_phant.push.stream_id "g6DJEnagnohd3pVnY1j5"
$ pipe config driver.pd_phant.push.private_key "g6DJEnagnohd3pVnY1j5"
$
$ # Configure the pipe to utilize specific drivers for push and pull
$ pipe config pipe.pull pd_grove_temperature
$ pipe config pipe.push pd_phant
$
$ # Try out the Pipe by running a pump once
$ pipe pump once
Running ./drivers/pd_phant/push --url="https://data.sparkfun.com" --stream_id="g6DJEnagnohd3pVnY1j5" --private_key="g6DJEnagnohd3pVnY1j5" `./drivers/pd_grove_temperature/pull --port="/dev/ttyACM0"`
$
$ # Configure a pump to run at an interval of 5 seconds and start it
$ pipe config pump.interval 5000
$ pipe pump start
```

**Comment by rjcorwin** [comment]
Released 0.1.0. Here's a working example. It requires node v0.10.26 due to a dependency on `node-hid` in `opk-temper1-cli` and a temper1 temperature sensor to pull data from.

```
#
# Step 0: Install the pipe command
#
npm install -g opk-pipe-cli

#
# Step 1: Create a new pipe
#
mkdir pipe1
cd pipe1
pipe init

#
# Step 2: Pull data from a sensor driver
#
# Add the temper1 temperature sensor driver and install it
git clone git@github.com:open-eio/opk-temper1-cli.git
./opk-temper1-cli/install
# Configure the driver. The configure command will give options you'll need
# and possible values for those options.
./opk-temper1-cli/configure
pipe config opk-temper1-cli.path USB_0c45_7401_14100000
# Configure the pipe to pull from this sensor and then test it
pipe config pipe.pull opk-temper1-cli
pipe pull

#
# Step 3: Push data to a database driver
#
# Add the phant database driver and configure it
git clone git@github.com:open-eio/opk-phant-cli.git
./opk-phant-cli/install
# Configure the driver. The configure command will give options you'll need
# and possible values for those options.
./opk-phant-cli/configure
pipe config opk-phant-cli.url http://data.sparkfun.com
pipe config opk-phant-cli.public_key RM1nQNbVRGtaMMgvVz8Y
pipe config opk-phant-cli.private_key lz6d0j7KxPH1VVryqMw5
pipe config opk-phant-cli.field_name temp
# Configure the pipe to push to this database and then test it
pipe config pipe.push opk-phant-cli
pipe push 42
# Check for your new data at https://data.sparkfun.com/streams/RM1nQNbVRGtaMMgvVz8Y

#
# Step 4: Configure the pump to run every five seconds and start it
#
pipe config pump.interval 5000
pipe pump
```

**Comment by rjcorwin** [comment]
@chrowe You can now try the above example with your temper1 USB sensors. If you are working with a fresh Raspberry Pi install and you need to get the node dependency, try this out...

```
wget http://node-arm.herokuapp.com/node_0.10.36_armhf.deb
sudo dpkg -i node_0.10.36_armhf.deb
```

**Comment by chrowe** [comment]
Thanks @rjsteinert 
Per #13 What do you suggest as a "fresh Raspberry Pi install"?

Also in https://github.com/open-eio/Open-Pipe-Kit-Project/wiki/Install-on-Raspberry-Pi I used a similar approach for installing node but installs v0.12.0 Should we suggest people lock their node version to 10.36 or is 12.x ok?

**Comment by rjcorwin** [comment]
Hi @chrowe - Raspbian sounds good to me. Glad to [see more contenders on the list at rpi.org](http://www.raspberrypi.org/downloads/) but I'm guessing Raspbian is going to be the most stable and supported for some time to come. On node, 0.10.x will be our go to until the node-hid library for interacting with USB devices reaches stable support for 0.12.x. They have a pull request I tested for 0.11.x and it worked so they are getting there.

**Comment by rjcorwin** [comment]
Updated docs https://github.com/open-eio/Open-Pipe-Kit-Project/wiki/Install-on-Raspberry-Pi

**Comment by rjcorwin** [comment]
@chrowe ^

**Comment by rjcorwin** [comment]
@chrowe Just tested opk-temer1-cli on Raspbian, it's failing when installing the dependency `node-hid`. That dependency is causing all sorts of issues.

```
make: Entering directory `/home/pi/Desktop/pipe1/opk-temper1-cli/node_modules/temper1x/node_modules/node-hid/build'

  CC(target) Release/obj.target/hidapi/hidapi/libusb/hid.o

../hidapi/libusb/hid.c:47:20: fatal error: libusb.h: No such file or directory
```

Related issue in node-hid issue queue -> https://github.com/node-hid/node-hid/issues/72

`node-hid` is causing all sorts of issues but it is a challenging task. They are trying to be a nodejs API for USB on all systems. I'm going to sleep on this issue.

**Comment by rjcorwin** [comment]
**phew** ... Wrote an exception for the Raspbian environment to run an alternative install. I have it running here, see at https://data.sparkfun.com/streams/pw1rY734M0c8wZopL1Xm

@chrowe Try it over on your end?

**Comment by chrowe** [comment]
@rjsteinert 
Seem to be having issues with ./opk-temper1-cli/configure
See https://gist.github.com/chrowe/7c3a683a16b53f52d6a5

FYI: Github requires that you have a valid ssh key to clone public repos.

**Comment by rjcorwin** [comment]
Here are some thoughts from today. Heading in the direction that the pipe cli, even pumps, are not necessarily needed. Instead, Sensor cli's should be stream generators.

Sensor cli's are stream generators that transmit data over STDOUT in CSV, adding data to the stream usually only when the value of the sensor changes.

```
$ ./opk-temper1-cli/pull --path USB_01
23,24,25,26,25, ...
```

Perhaps some sensors cli's allow you to tweak the sensitivity.

```
$ ./opk-temper1-cli/pull --path USB_01 --threshold .5
23,25.5,24,24.5,25,25.5,26,25.5,25, ...
```

Database cli's capture streams over STDIN, parse those streams as CSV, and transmit them to somewhere else.

```
$ ./opk-temper1-cli/pull --path USB_01 | ./opk-phant-cli/push --url ...
```

Use the Unix `tee` cli to backup that stream to file and pass it on.

```
$ ./opk-temper1-cli/pull --path USB_01 | tee backup.csv | ./opk-phant-cli/push --url ...
$ backup.csv
23,24,25,26,25, ...
```

I'm thinking about writing a `teetime` cli as a way to backup with timestamps and send the data to database cli's that want to receive a timestamp with their data.

```
$ ./opk-temper1-cli/pull --path USB_01 | teetime backup.csv | ./opk-phant-cli/push --url ...
$ cat backup.csv
2015-03-17 09:15:32, 24
2015-03-17 09:45:03, 25
...
```

Would a `flowcontrol` be helpful?

```
$ ./opk-temper1-cli/pull --path USB_01 | flowcontrol --capacity 10 | ./opk-phant-cli/push --url ...
```

**Comment by rjcorwin** [comment]
To stream data into a Dat database, you could do something like...

```
$ ./opk-temper1-cli/pull --path USB_01 | teetime | dat import --csv --newline $'\r\n'
```

**Comment by rjcorwin** [comment]
I refactored opk-temper1-cli to focus on pipe streams. This is working...

```
mkdir data;
cd data;
wget https://github.com/open-eio/opk-temper1-cli/archive/0.2.1.zip
unzip 0.2.1.zip
./opk-temper1-cli-0.2.1/install
./opk-temper1-cli-0.2.1/help
dat init
./opk-temper1-cli-0.2.1/pull --path USB_0c45_7401_14200000 | dat import --csv
```

You can then monitor the data by running the following in the data folder...

```
watch -n1 "dat cat | tail"
```

Note that the sensor cli will only stream data if it sees a difference more than 1 degree. You can change this with the `--threshold` option. Also note, if running from an R-Pi, you may need to turn up the timeout over 1 second because the Pi may never be able to return a value in that amount of time.
